## 使用TensorBoard 

In [1]:
import tensorflow as tf

a=tf.constant(2)
b=tf.constant(3)

x=tf.add(a,b)

with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs',sess.graph)
	print(sess.run(x))
	
writer.close()

5


（以Anaconda3为例）创建python文件并保存在桌面

打开Anaconda Prompt并来到桌面路径下运行PYTHON脚本

运行tensorboad, 它会访问之前脚本创建的graphs文件夹。之后在控制台会显示访问路径。例如 http://WIN10-711010523:6006 将地址粘到浏览器可以看到graph

![](C:\Users\Administrator\Desktop\1.png)

接下来将输入节点的名称做一下修改

In [2]:
import tensorflow as tf

a=tf.constant(2,name="a")#用name修改节点名称
b=tf.constant(3,name="b")

x=tf.add(a,b,name="add")


with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs',sess.graph)
	print(sess.run(x))

5


还像之前一样在终端分别运行PYTHON脚本与tensorboard。如果之前浏览器还开着之前tensorboard页面，需要先关闭再重新开启，不然终端会有这样的提示

## Constant 类型

In [7]:
import tensorflow as tf
a=tf.constant([2,2],name='a')#创建constant
b=tf.constant([[0,1],[2,3]],name="b")
add=tf.add(a,b,name="add")
mul=tf.multiply(a,b,name="mul")
with tf.Session() as sess:
    x,y=sess.run([add,mul])
    print(x,y)

[[2 3]
 [4 5]] [[0 2]
 [4 6]]


创建constant类型的例子

## 特殊赋值

In [14]:
zeros=tf.zeros([2,3],tf.int32)
with tf.Session() as sess:
    result=sess.run(zeros)
    print(result)

[[0 0 0]
 [0 0 0]]


创建指定大小的zeros矩阵

In [18]:
input_tensor=tf.constant([[0,1],[2,3],[4,5]],name="input_tensor")
zeros=tf.zeros_like(input_tensor)#指定zeros矩阵的大小
with tf.Session() as sess:
    result=sess.run(zeros)
    print(result)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
根据传入的矩阵尺寸创建zeros矩阵

其它类似的函数:


** ones **
* tf.ones(shape,dtype=tf.float32,name=None)
* tf.ones_like(input_tensor,dtype=None,name=None,optimize=True)

In [20]:
matrix=tf.fill([2,3],8)

with tf.Session() as sess:
    result=sess.run(matrix)
    print(result)

[[8 8 8]
 [8 8 8]]


在矩阵内添加指定数值

In [23]:
import numpy as np
tf.int32==np.int32

True

In [24]:
matrix=tf.ones([2,2],np.float32)

with tf.Session() as sess:
    result=sess.run(matrix)
    print(result)

[[ 1.  1.]
 [ 1.  1.]]


tf数据输出为numpy array

In [25]:
my_const=tf.constant([1.0,2.0],name="my_const")
with tf.Session() as sess:b
    print(sess.graph.as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }

打印graph def

## Variables
Variable 是一个类，constant 是一种op

初始化variable

In [26]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

初始化全部variables

In [31]:
init_ab=tf.variables_initializer([a,b],name="init_ab")
with tf.Session() as sess:
    sess.run(init_ab)b

AttributeError: 'Tensor' object has no attribute 'initializer'

初始化部分variables但是报错

In [32]:
W=tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)

初始化单独一个variable

In [34]:
#初始化大小700X100的随机数值矩阵
W=tf.Variable(tf.truncated_normal([700,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W)
    print(W.eval())

<tf.Variable 'Variable_2:0' shape=(700, 10) dtype=float32_ref>
[[-1.64373493  1.38142228  0.02620468 ...,  0.03384978 -1.18727875
  -0.30884752]
 [ 1.10493028 -0.39550069 -0.03230183 ...,  0.4909828   0.55792344
  -1.59890783]
 [-0.44164404  0.69113725 -0.86431575 ...,  0.27377507 -1.64605892
   0.84873748]
 ..., 
 [-1.36063004  0.99020559  0.57447302 ..., -0.20169938 -0.09743395
  -1.45789444]
 [ 0.30184504 -0.51223069 -1.18259192 ..., -0.5938319   1.26349866
   0.19031805]
 [ 0.96660119  0.90686685 -1.39591968 ...,  0.13805443  0.88506061
   1.22530198]]


## Variable的赋值方法

In [36]:
W=tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

10


W.assign(100)并没有真正赋值给W，只是做了一下运算。此处需要放在session里才能赋值

In [38]:
W=tf.Variable(10)
assign_op=W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval())

100


在session加入运算后赋值成功。赋值不用初始化variable因为assign_op一直执行了这一动作。数值初始化本身就是赋值的一类，只不过是专门赋值初始数值的op

In [42]:
#其它赋值方式
my_var=tf.Variable(2,name="my_var")
my_var_times_two=my_var.assign(2*my_var)
with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)#>>4
    sess.run(my_var_times_two)#>>8
     sess.run(my_var_times_two)#>>16

In [ ]:
#其它赋值方式
my_var=tf.Variable(10)
With tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var.assign_add(10))#>>20
    sess.run(my_var.assign_sub(2))#>>18

assign_add()与assign_sub()不能初始化variable,只能用my_var的数值

In [51]:
#每个session包含各自的variable
W=tf.Variable(10)

sess1=tf.Session()
sess2=tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))


20
8


In [52]:
#每个session包含各自的variable
W=tf.Variable(10)

sess1=tf.Session()
sess2=tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

20
8
120
-42


In [53]:
#用一个Variable初始化另一个Variable

#W是个700X100的随机矩阵
W=tf.Variable(tf.truncated_normal([700,10]))
U=tf.Variable(2*W)

## Session 与 InteractiveSession

In [55]:
sess = tf.InteractiveSession()
a=tf.constant(5.0)
b=tf.constant(6.0)
c=a*b

print(c.eval()) #在InteractiveSession下，无需像之前那样指定session
sess.close()

30.0


声明tf.InteractiveSession()后无需再次指定session,可以直接运算

## Control Dependency

用来指定运算顺序

## Placeholder 占位

如同公式f(x,y)=x*2+y一样，我们无需知道x,y的确切数值就可以编辑公式

In [58]:
#创建一个placeholder
a=tf.placeholder(tf.float32,shape=[3]) #建议一开始设置好数据类型

b=tf.constant([5,5,5],tf.float32)

c=a+b

with tf.Session() as sess:
    print(sess.run(c,{a:[1,2,3]}))  #向placeholder传入dict 赋值
                                    #每回只能做一次赋值

[ 6.  7.  8.]


## 更改op的数值

In [61]:
a=tf.add(2,5)
b=tf.multiply(a,3)

with tf.Session() as sess:
    #将a的数值替换为15
    replace_dict={a:15}
    sess.run(b,feed_dict=replace_dict)#将replace_dict的数值传给feed_dict
    

## Lazy Loading

直到需要时再初始化对象

In [63]:
#普通loading,需要把所有op全部写出来
x=tf.Variable(10,name='x')
y=tf.Variable(20,name='y')
z=tf.add(x,y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(z)

In [64]:
#lazy loading
x=tf.Variable(10,name='x')
y=tf.Variable(20,name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(10):
        sess.run(tf.add(x,y))  #把最后一步运算放到这里

## 运行千次OP时的建议

* 将op定义与计算/运行分开
* 使用python property 编写function